name: SoapUI Tests

on:
  push:
    branches:
      - main

jobs:
  soapui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download and Run SoapUI Tests
        run: |
          docker run -i --rm \
          -v .:/opt/soapui/projects \
          -v tests:/opt/soapui/projects/testresult \
          lukastosic/docker-soapui \
          -s "Log in testing" \
          -r -j \
          -f /opt/soapui/projects/testresult \
          -I "/opt/soapui/projects/Soap-try-soapui-project.xml"
